import { useMemo } from 'react'
import {
  buildProjectSearchGroups,
  type ProjectSearchOptions,
} from '../domain/projectSearch'

export const useStylePreviewProjectSearchGroups = ({
  attributeDefinitions,
  attributeGroups,
  catalogEntriesByCatalogId,
  catalogGroupsByCatalogId,
  catalogs,
  getObjectSectionLabel,
  objectsByType,
  onOpenAttributes,
  onOpenCatalog,
  onOpenCatalogEntry,
  onOpenObject,
  onOpenRelation,
  onOpenTimelineEvent,
  query,
  relationGraph,
  timelineEvents,
  ui,
}: ProjectSearchOptions) =>
  useMemo(
    () =>
      buildProjectSearchGroups({
        attributeDefinitions,
        attributeGroups,
        catalogEntriesByCatalogId,
        catalogGroupsByCatalogId,
        catalogs,
        getObjectSectionLabel,
        objectsByType,
        onOpenAttributes,
        onOpenCatalog,
        onOpenCatalogEntry,
        onOpenObject,
        onOpenRelation,
        onOpenTimelineEvent,
        query,
        relationGraph,
        timelineEvents,
        ui,
      }),
    [
      attributeDefinitions,
      attributeGroups,
      catalogEntriesByCatalogId,
      catalogGroupsByCatalogId,
      catalogs,
      getObjectSectionLabel,
      objectsByType,
      onOpenAttributes,
      onOpenCatalog,
      onOpenCatalogEntry,
      onOpenObject,
      onOpenRelation,
      onOpenTimelineEvent,
      query,
      relationGraph,
      timelineEvents,
      ui,
    ],
  )
