// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StoryDB.Api.Data;

#nullable disable

namespace StoryDB.Api.Migrations
{
    [DbContext(typeof(StoryDbContext))]
    [Migration("20260609102341_AddStoryObjectHierarchySelections")]
    partial class AddStoryObjectHierarchySelections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttributeGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeGroupId");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("ProjectId", "ObjectTypeId", "Name")
                        .IsUnique();

                    b.ToTable("AttributeDefinitions");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("ProjectId", "ObjectTypeId", "Name")
                        .IsUnique();

                    b.ToTable("AttributeGroups");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("HierarchyGroups");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyLink", b =>
                {
                    b.Property<int>("ParentNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("ChildNodeId")
                        .HasColumnType("integer");

                    b.HasKey("ParentNodeId", "ChildNodeId");

                    b.HasIndex("ChildNodeId");

                    b.ToTable("HierarchyLinks");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("HierarchyNodes");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.ObjectAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<int>("StoryObjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("StoryObjectId", "AttributeDefinitionId")
                        .IsUnique();

                    b.ToTable("ObjectAttributes");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.ObjectType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Key")
                        .IsUnique();

                    b.ToTable("ObjectTypes");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverImagePath")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.StoryObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DataJson")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ObjectTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ObjectTypeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Objects");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.StoryObjectHierarchySelection", b =>
                {
                    b.Property<int>("StoryObjectId")
                        .HasColumnType("integer");

                    b.Property<int>("HierarchyGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("HierarchyNodeId")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("StoryObjectId", "HierarchyGroupId", "HierarchyNodeId");

                    b.HasIndex("HierarchyGroupId");

                    b.HasIndex("HierarchyNodeId");

                    b.ToTable("StoryObjectHierarchySelections");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeDefinition", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.AttributeGroup", "AttributeGroup")
                        .WithMany("Definitions")
                        .HasForeignKey("AttributeGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("StoryDB.Api.Data.Entities.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeGroup");

                    b.Navigation("ObjectType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeGroup", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.ObjectType", "ObjectType")
                        .WithMany()
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyGroup", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyLink", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.HierarchyNode", "ChildNode")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.HierarchyNode", "ParentNode")
                        .WithMany("ChildLinks")
                        .HasForeignKey("ParentNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildNode");

                    b.Navigation("ParentNode");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyNode", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.HierarchyGroup", "Group")
                        .WithMany("Nodes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.ObjectAttribute", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.AttributeDefinition", "AttributeDefinition")
                        .WithMany("ObjectAttributes")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.StoryObject", "StoryObject")
                        .WithMany("Attributes")
                        .HasForeignKey("StoryObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("StoryObject");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.ObjectType", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.Project", "Project")
                        .WithMany("ObjectTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.Project", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.AppUser", "OwnerUser")
                        .WithMany("Projects")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OwnerUser");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.StoryObject", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.ObjectType", "ObjectType")
                        .WithMany("Objects")
                        .HasForeignKey("ObjectTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.Project", "Project")
                        .WithMany("Objects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ObjectType");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.StoryObjectHierarchySelection", b =>
                {
                    b.HasOne("StoryDB.Api.Data.Entities.HierarchyGroup", "HierarchyGroup")
                        .WithMany()
                        .HasForeignKey("HierarchyGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.HierarchyNode", "HierarchyNode")
                        .WithMany()
                        .HasForeignKey("HierarchyNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StoryDB.Api.Data.Entities.StoryObject", "StoryObject")
                        .WithMany("HierarchySelections")
                        .HasForeignKey("StoryObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HierarchyGroup");

                    b.Navigation("HierarchyNode");

                    b.Navigation("StoryObject");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AppUser", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeDefinition", b =>
                {
                    b.Navigation("ObjectAttributes");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.AttributeGroup", b =>
                {
                    b.Navigation("Definitions");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyGroup", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.HierarchyNode", b =>
                {
                    b.Navigation("ChildLinks");

                    b.Navigation("ParentLinks");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.ObjectType", b =>
                {
                    b.Navigation("Objects");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.Project", b =>
                {
                    b.Navigation("ObjectTypes");

                    b.Navigation("Objects");
                });

            modelBuilder.Entity("StoryDB.Api.Data.Entities.StoryObject", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("HierarchySelections");
                });
#pragma warning restore 612, 618
        }
    }
}
